version: '3.8'

services:
  mysql:
    image: mysql:8.0.13
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mislu_market
      MYSQL_DATABASE: market
      MYSQL_ROOT_HOST: '%'
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - app-network

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.es
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data 
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"   # AMQP协议端口
      - "15672:15672" # 管理界面端口
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge